# Generated by Django 2.2 on 2019-06-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='showcase',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
