# Generated by Django 2.2 on 2019-06-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogweb', '0002_post_showcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_image',
            field=models.ImageField(default='https://i.pinimg.com/originals/3e/9b/50/3e9b50f473182f34b86dc00d80ddf843.jpg', upload_to='headres/'),
        ),
    ]
